### ISSUE TITLE
Use cspell for lightweight language check

### ISSUE THREAD

**Issue by daniel-vera-g** [daniel-vera-g/typo#1]
> https://www.npmjs.com/package/cspell

- https://seankilleen.com/2021/01/adding-spell-checking-to-my-blogs-build-process-with-github-actions-and-cspell/

Sample gh actions config:

```yml
cspells-spellchecking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out the code
      - uses: actions/setup-node@v1
        name: Run spell check
        with:
          node-version: "12"
      - run: npm install -g cspell
      - run: |
          cspell --config ./vscode/cspell.json README.md
```
